// Solstice Games © 2024. All Rights Reserved.

#ifndef SOLID_MACROS_STANDARD_SOLID_OPTIONAL_H
#define SOLID_MACROS_STANDARD_SOLID_OPTIONAL_H

#include "CoreMinimal.h"

#endif // SOLID_MACROS_STANDARD_SOLID_OPTIONAL_H